# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hetaddon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementvalue',
            name='value',
            field=models.TextField(),
        ),
    ]
