# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hetaddon', '0002_auto_20170123_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(null=True, through='hetaddon.Membership', to='hetaddon.User'),
        ),
    ]
