# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hetaddon', '0003_auto_20170123_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(through='hetaddon.Membership', to='hetaddon.User'),
        ),
    ]
