# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-29 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hetaddon', '0004_auto_20170126_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalplatform',
            name='platform_id',
        ),
        migrations.AddField(
            model_name='document',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requirement',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='externalplatform',
            name='platform_name',
            field=models.CharField(choices=[('atl', 'Atlassian'), ('fac', 'Facebook'), ('goo', 'Google')], max_length=3),
        ),
        migrations.AlterField(
            model_name='externalplatform',
            name='user_ext_id',
            field=models.CharField(max_length=128),
        ),
    ]
