# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hetaddon', '0005_auto_20170129_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[(b'cal', b'Call for Proposal'), (b'rul', b'Rules/Limitations'), (b'tem', b'Template'), (b'oth', b'Other')], max_length=3),
        ),
        migrations.DeleteModel(
            name='DocumentCategory',
        ),
    ]
