# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hetaddon', '0006_auto_20170130_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.BinaryField(null=True),
        ),
    ]
