# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hetaddon', '0007_document_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300)),
                ('disabled', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='disabled',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='document',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='value',
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('cal', 'Call for Proposal'), ('rul', 'Rules/Limitations'), ('tem', 'Template'), ('oth', 'Other')], max_length=3),
        ),
        migrations.AddField(
            model_name='requirementvalue',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hetaddon.Document'),
        ),
        migrations.AddField(
            model_name='requirementvalue',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hetaddon.Requirement'),
        ),
    ]
