# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hetaddon', '0008_auto_20170202_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementvalue',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
