# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hetaddon', '0010_tenantinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantinfo',
            name='client_key',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
