# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hetaddon', '0011_auto_20170214_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RootFolder',
            fields=[
                ('folder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hetaddon.Folder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hetaddon.User')),
            ],
            bases=('hetaddon.folder',),
        ),
        migrations.RemoveField(
            model_name='project',
            name='folder',
        ),
        migrations.AddField(
            model_name='projectfolder',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hetaddon.Folder'),
        ),
        migrations.AddField(
            model_name='projectfolder',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hetaddon.Project'),
        ),
        migrations.AddField(
            model_name='folder',
            name='projects',
            field=models.ManyToManyField(through='hetaddon.ProjectFolder', to='hetaddon.Project'),
        ),
    ]
